// Autogenerated by Nightwatch
// Refer to the online docs for more details: https://nightwatchjs.org/gettingstarted/configuration/
// const Services = {}; loadServices();

// require('babel-register')() // or 
// require('babel-core/register')
// require("@babel/register");
import {register} from "babel"
// experimentally
// require("@babel/preset-typescript");

// TODO: add the eslint exception
const src_folders = ["build"];
const webdriver = {
  start_process: true,
  server_path: "node_modules/.bin/chromedriver",
  port: 9515
};

const headed = {
  src_folders,
  webdriver,
  test_settings: {
    default: {
      desiredCapabilities: {
        browserName: "chrome"
      },
      custom_commands_path: "custom-commands",
      launch_url: "https://nightwatch-demo.netlify.com/",
      globals: {
        timeToWait: 1001
      }
    }
  }
};

const headless = {
  src_folders,
  webdriver,
  test_settings: {
    default: {
      desiredCapabilities: {
        browserName: "chrome",
        chromeOptions: {
          args: ["headless"]
        }
      },
      custom_commands_path: "custom-commands",
      launch_url: "https://nightwatch-demo.netlify.com/",
      globals: {
        timeToWait: 1001
      }
    }
  }
};

// TODO: probably, add a switch between headed and headless
module.exports = headed;
